---
title: "Get on your bike"
author: "Kuznik et al."
date: "2024-11-13"
output: pdf_document
---

# 1. Introduction 
The rapid urbanisation of recent decades has seen cities face challenges such as traffic congestion, air pollution, and limited parking spaces. In the face of these issues, rental bike systems have gained significant popularity, offering a cheap and eco-friendly alternative to more traditional commuting methods. Rental bikes provide a practical solution for short-distance travel, be it for students going to school, office workers heading to the workplace and even tourists exploring a city. In addition to promoting an active lifestyle, they eliminate the hassle of bike ownership, such as storage and maintenance. The growing demand of rental bike companies is reflected in the global market value of bike rentals, projected to reach a value of $11.3 billion in 2031, marking a 538% increase from the 2021 market value of $2.1 billion (Allied Market Research, 2021).
	The biggest challenge rental bike companies face is ensuring constant availability of bikes, as demand can fluctuate due to  numerous reasons. Bikes must be readily accessible to users at all times, making it essential for company leaders to be aware of peak hours, the impact of weather conditions and high-demand areas. In this project, we will use various machine learning models to predict the number of rented bikes required to meet customer demand under different circumstances, trying to figure out which of them performs best. The goal is to assist a fictional bike rental company operating in Seoul, South Korea, in planning the optimal size of their bike fleet.

# Dataset
To conduct our analysis, we will use a dataset called „Seoul Bike Sharing Demand“ which contains the count of public bicycles rented per hour in the Seoul Bike Sharing System with corresponding weather data and holiday information, collected between 2017 and 2018 (UCI Machine Learning Repository, 2020). We will enrich the dataset by adding columns that capture different times-related factors, such as whether a given day is a working day or a weekend. Additionally, we will categorise hours into specific periods to better capture daily trends in bike demand. 

# Structure
We will begin by examining the dataset and outlining the specific changes we made for the purpose of our analysis. Next, we will perform exploratory data analysis, focussing on correlations between variables to address potential multicollinearity issues. In the following chapters, we will fit different machine learning models to the data and use their results to predict the number of rental bikes needed in Seoul. The sequence of the models will be as follows: a linear model, a generalised linear model with a Poisson family, another with a Binomial family, a generalised additive model, a neural network and a support vector machine. Finally, we will compare these models to identify the best solution for our bike rental company.

```{r, echo = TRUE}


```

# 2. Data Transformation
The raw dataset was unsuitable for analysis and therefore required transformation. Seeing as the column names were unnecessarily complex and inconsistent, the first step was renaming them for simplicity. "Temperature.캜." was changed to "Temperature", "Humidity..." to "Humidity", "Visibility..10m." to "Visibility" and so forth. In the categorical variable "Functioning.Day", which indicated whether a given day was functioning for bike rentals, non-functioning days were removed as the number of rented bikes was obviously zero on those days. The column was subsequently dropped since its remaining values were identical, making it redundant.
  Next, time-related features were added to capture their potential impact on rented bikes. "Month" and "Weekday" columns were created to indicate the month and day of the week, followed by an "Is.Weekend" column to classify days as working days or weekends. To catch meaningful variations within a single day, the "Hours" column was grouped into segments such as morning rush hour, evening rush hour and late night. These segments were stored in a new variable "TimeOfDay". Finally, all categorical variables were converted to factor data types, completing the preparation of the dataset for analysis.


3. Exploratory data analysis

4. Modeling 
  a) Linear Model
    i) Model implementation
    ii) Result interpretation
    ii) Cross Validation*

  b) Generalised Linear Model with family set to Poisson
    i) Model implementation
    ii) Result interpretation
    ii) Cross Validation*
    
  c) Generalised Linear Model with family set to Binomial
    i) Model implementation
    ii) Result interpretation
    ii) Cross Validation*
    
  d) Generalised Additive Model
    i) Model implementation
    ii) Result interpretation
    ii) Cross Validation*

  e) Support Vector Machine (SVM)
    i) Model implementation
    ii) Result interpretation
    ii) Cross Validation*

  f) Neural Network
    i) Model implementation
    ii) Result interpretation
    ii) Cross Validation*

5. Usage of AI

6. Conclusion
